branches:
  only: 
    - next
matrix:
  include:
    - stage: "Build webpack and Test"
      os: osx
      env:
        - Webpack="iOS"
      osx_image: xcode10.0
      language: node_js 
      node_js: "10"
      jdk: oraclejdk8
      before_script:
        - pod repo update
        - cd ../demo && tns platform add ios@next
      script: ../cd demo && npm run build.plugin && npm i && tns build ios --bundle --env.uglify
    - os: linux
      language: android
      dist: trusty
      env:
        - Webpack="Android"
      jdk: oraclejdk8
      before_install: nvm install 10
      before_script:
        - cd ../demo && tns platform add android@next
      script: cd ../demo && npm run build.plugin && npm i && tns build android --bundle --env.uglify --env.snapshot
    - os: linux
      language: android
      dist: trusty
      jdk: oraclejdk8
      env: 
        - Android="UnitTests"
      before_script:
        - echo no | android create avd --force -n test -t android-21 -b armeabi-v7a
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator
        - cd ../demo && tns platform add android@next
      before_install:
        - nvm install 10
      script:
        - cd ../src && npm i && npm run tsc && npm run tslint && cd ../demo && tns build android
        - travis_wait travis_retry tns test android --justlaunch
    - os: osx
      language: node_js
      node_js: "10"
      jdk: oraclejdk8
      env: 
        - iOS="UnitTests"
      osx_image: xcode10.0
      before_script:
        - pod repo update
        - cd demo && tns platform add ios@next
      script: 
        - cd ../src && npm i && npm run tsc && npm run tslint && cd ../demo && tns build ios
        - travis_wait travis_retry tns test ios --justlaunch

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-21
    - android-28
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

before_install:
    - sudo pip install --upgrade pip
    - sudo pip install six

install:
    - echo no | npm install -g nativescript@next
    - tns usage-reporting disable
    - tns error-reporting disable
    - cd src
    - npm install tns-core-modules@next -D
    - cd ../demo
    - npm install tns-core-modules@next -P
    - npm install nativescript-dev-webpack@next -D
    - npm install nativescript-dev-typescript@next -D
    - ./node_modules/.bin/update-ns-webpack --deps --configs
    - npx rimraf -- hooks node_modules platforms package-lock.json
